apiVersion: v1
kind: ConfigMap
metadata:
  name: icecast-config
  namespace: icecast-ns
data:
  icecast.xml: |
    <?xml version="1.0"?>
    <icecast>
        <limits>
            <clients>100</clients>
            <sources>2</sources>
            <queue-size>524288</queue-size>
            <client-timeout>30</client-timeout>
            <header-timeout>15</header-timeout>
            <timelimit>36000</timelimit>
            <burst-size>65536</burst-size>
        </limits>

        <authentication>
            # Las contraseñas se inyectarán desde el Secret en el Deployment
            <source-password>${ICECAST_SOURCE_PASSWORD}</source-password>
            <relay-password>${ICECAST_RELAY_PASSWORD}</relay-password>
            <admin-user>admin</admin-user>
            <admin-password>${ICECAST_ADMIN_PASSWORD}</admin-password>
        </authentication>

        <hostname>streaming.dmarmijosa.com</hostname> # Tu dominio público
        <listen-socket>
            <port>8000</port> # Puerto interno de Icecast
        </listen-socket>

        <files>
            <paths>
                <basedir>/usr/share/icecast2</basedir>
                <logdir>/var/log/icecast2</logdir>
                <webroot>/usr/share/icecast2/web</webroot>
                <adminroot>/usr/share/icecast2/admin</adminroot>
            </paths>
        </files>

        <security>
            <chroot>0</chroot>
        </security>
        <log>
            <level>warn</level> # info, warn, error, debug
            <size>10000</size> # Max size of error log in Kb
        </log>
    </icecast>