apiVersion: v1
kind: ConfigMap
metadata:
  name: icecast-config
  namespace: icecast-ns
data:
  icecast.xml: |
    <icecast>
        <location>Ciutadella de Menorca, Spain</location> # Ajustado a tu ubicación
        <admin>dmarmijosa@example.com</admin> # Ajustado a tu email

        <limits>
            <clients>100</clients>
            <sources>2</sources>
            <queue-size>524288</queue-size>
            <client-timeout>30</client-timeout>
            <header-timeout>15</header-timeout>
            <source-timeout>10</source-timeout>
            <burst-on-connect>1</burst-on-connect>
            <burst-size>65535</burst-size>
        </limits>

        <authentication>
            <source-password>${ICECAST_SOURCE_PASSWORD}</source-password> # Ajustado para usar Secret
            <relay-password>${ICECAST_RELAY_PASSWORD}</relay-password>   # Ajustado para usar Secret

            <admin-user>admin</admin-user>
            <admin-password>${ICECAST_ADMIN_PASSWORD}</admin-password>   # Ajustado para usar Secret
        </authentication>

        <hostname>icecast.dmarmijosa.com</hostname> # Ajustado a tu dominio

        <listen-socket>
            <port>8000</port>
            </listen-socket>
        <http-headers>
            <header name="Access-Control-Allow-Origin" value="*" />
        </http-headers>


        <fileserve>1</fileserve>

        <paths>
            <basedir>/usr/share/icecast</basedir>

            <logdir>/var/log/icecast</logdir> # CRÍTICO: Ajustado a la ruta del XML por defecto
            <webroot>/usr/share/icecast/web</webroot> # Ajustado a la ruta del XML por defecto
            <adminroot>/usr/share/icecast/admin</adminroot> # Ajustado a la ruta del XML por defecto
            <alias source="/" destination="/status.xsl"/> # Presente en el XML por defecto
            </paths>

        <logging>
            <accesslog>access.log</accesslog>
            <errorlog>-</errorlog>
            <loglevel>3</loglevel> <logsize>10000</logsize> </logging>

        <security>
            <chroot>0</chroot>
            </security>
    </icecast>