apiVersion: apps/v1
kind: Deployment
metadata:
  name: icecast-deployment
  namespace: icecast-ns
  labels:
    app: icecast
spec:
  replicas: 1
  selector:
    matchLabels:
      app: icecast
  template:
    metadata:
      labels:
        app: icecast
    spec:
      # NO HAY initContainers AQUI (los habíamos quitado en la última iteración)
      containers:
        - name: icecast-container
          image: libretime/icecast:latest
          ports:
            - containerPort: 8000
          env:
            - name: ICECAST_SOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: icecast-secrets
                  key: ICECAST_SOURCE_PASSWORD
            - name: ICECAST_RELAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: icecast-secrets
                  key: ICECAST_RELAY_PASSWORD
            - name: ICECAST_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: icecast-secrets
                  key: ICECAST_ADMIN_PASSWORD
          volumeMounts:
            # Montar el ConfigMap en la ruta donde la imagen espera el archivo de configuración
            - name: icecast-config-volume
              mountPath: /etc/icecast.xml # Ruta donde Icecast espera su config
              subPath: icecast.xml        # Nombre del archivo dentro del ConfigMap
              readOnly: true              # Es importante que sea read-only
            # Montar el volumen de logs en la ruta ESPERADA por Icecast
            - name: icecast-logs-storage
              mountPath: /var/log/icecast # Ruta donde Icecast espera sus logs
          # --- CAMBIO AQUÍ: Eliminamos 'command' y no usamos 'args' si queremos el CMD por defecto ---
          # Si quieres usar el CMD por defecto de la imagen (icecast -c /etc/icecast.xml),
          # simplemente ELIMINA la sección 'command' y 'args' completamente.
          # La imagen se iniciará con su ENTRYPOINT y CMD predeterminados.
      volumes:
        - name: icecast-config-volume
          configMap:
            name: icecast-config
        - name: icecast-logs-storage
          persistentVolumeClaim:
            claimName: icecast-logs-pvc