apiVersion: apps/v1
kind: Deployment
metadata:
  name: icecast-deployment
  namespace: icecast-ns
  labels:
    app: icecast
spec:
  replicas: 1
  selector:
    matchLabels:
      app: icecast
  template:
    metadata:
      labels:
        app: icecast
    spec:
      # --- INICIA NUEVA SECCIÓN: initContainers ---
      # Este initContainer copiará el icecast.xml del ConfigMap a un volumen temporal escribible.
      initContainers:
        - name: copy-icecast-config
          image: busybox:1.36 # Imagen ligera para copiar archivos
          command: ["sh", "-c", "cp /tmp/icecast-config/icecast.xml /var/run/icecast/icecast.xml && chmod 666 /var/run/icecast/icecast.xml"] # Copia y asegura permisos
          volumeMounts:
            # Monta el ConfigMap como solo lectura en un directorio temporal
            - name: icecast-config-volume
              mountPath: /tmp/icecast-config
            # Monta el volumen temporal escribible donde se copiará el archivo
            - name: icecast-writable-config-volume
              mountPath: /var/run/icecast # Monta el directorio donde Icecast buscará el archivo
      # --- FIN NUEVA SECCIÓN ---
      containers:
        - name: icecast-container
          image: libretime/icecast:latest
          ports:
            - containerPort: 8000
          env:
            - name: ICECAST_SOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: icecast-secrets
                  key: ICECAST_SOURCE_PASSWORD
            - name: ICECAST_RELAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: icecast-secrets
                  key: ICECAST_RELAY_PASSWORD
            - name: ICECAST_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: icecast-secrets
                  key: ICECAST_ADMIN_PASSWORD
          volumeMounts:
            # Monta el volumen temporal escribible donde está el icecast.xml copiado
            - name: icecast-writable-config-volume
              mountPath: /var/run/icecast # Monta el directorio donde Icecast buscará el archivo
            # Montar el volumen de logs en la ruta ESPERADA por Icecast
            - name: icecast-logs-storage
              mountPath: /var/log/icecast # La ruta que viene en el XML por defecto
      # --- CAMBIO AQUÍ: Usamos 'args' para pasar la ruta del config al ENTRYPOINT por defecto ---
          args: ["icecast", "-c", "/var/run/icecast/icecast.xml"] # Pasamos el path del config al ENTRYPOINT de la imagen
      volumes:
        - name: icecast-config-volume
          configMap:
            name: icecast-config
        # --- NUEVA SECCIÓN: Volumen temporal escribible ---
        - name: icecast-writable-config-volume
          emptyDir: {} # Un volumen temporal que se crea con el pod
        # --- FIN NUEVA SECCIÓN ---
        - name: icecast-logs-storage
          persistentVolumeClaim:
            claimName: icecast-logs-pvc