apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: icecast-ingress
  namespace: icecast-ns
  annotations:
    # Anotación para que cert-manager emita el certificado
    cert-manager.io/cluster-issuer: "letsencrypt-prod" # Asegúrate que este nombre es correcto
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP" # Icecast usa HTTP

    # NUEVO: Anotación para forzar reescritura de la URL si el path "/" no funciona
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: public # Asegúrate que esta clase es correcta para tu MicroK8s Ingress
  rules:
    - host: "icecast.dmarmijosa.com" # LO CAMBIAREMOS LUEGO A icecast.dmarmijosa.com
      http:
        paths:
          - path: /(.*) # Captura cualquier ruta después de /
            pathType: Prefix
            backend:
              service:
                name: icecast-service
                port:
                  number: 8000
  tls: # ESTA SECCIÓN DEBE ESTAR DESCOMENTADA Y BIEN CONFIGURADA
    - hosts:
        - "icecast.dmarmijosa.com" # LO CAMBIAREMOS LUEGO A icecast.dmarmijosa.com
      secretName: icecast-tls-secret # Nombre del Secret donde cert-manager guardará el certificado